use serde::{Deserialize, Serialize};

use crate::{Confidence, EventMeta};

/// Category of a generated insight.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash, specta::Type)]
#[serde(rename_all = "snake_case")]
pub enum InsightCategory {
    Network,
    Battery,
    Storage,
    Privacy,
    Behavior,
    Usage,
    Thermal,
    Resource,
}

/// Severity level of an insight.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, PartialOrd, Ord, specta::Type)]
#[serde(rename_all = "snake_case")]
pub enum InsightSeverity {
    Info,
    Warning,
    Critical,
}

/// A user-facing insight generated by the analytics/insights engine.
#[derive(Debug, Clone, Serialize, Deserialize, specta::Type)]
pub struct InsightEvent {
    pub meta: EventMeta,
    pub category: InsightCategory,
    pub severity: InsightSeverity,
    pub title: String,
    pub description: String,
    pub technical_detail: Option<String>,
    pub package_name: Option<String>,
    pub confidence: Confidence,
}
